    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: set up jdk1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: checkout
            uses: actions/checkout@v2
          - name: do test
            uses: education/autograding@v1
