name: Java CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
